# Generated by Django 5.2.7 on 2025-11-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('instructor', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('schedule', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='studentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('course_id', models.IntegerField()),
            ],
        ),
    ]
