# Generated by Django 5.2.7 on 2025-10-28 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='uiversity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='university_id',
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='univ',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.uiversity'),
        ),
    ]
