# Generated by Django 5.2.7 on 2025-10-28 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_uiversity_remove_student_university_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('instructor', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('schedule', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='univ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.uiversity'),
        ),
        migrations.CreateModel(
            name='studentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
