# Generated by Django 5.2.7 on 2025-11-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_course_alter_student_univ_studentcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='student_id',
            field=models.IntegerField(),
        ),
    ]
