# Generated by Django 5.2.7 on 2025-11-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_studentcourse_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='univ',
            field=models.IntegerField(),
        ),
    ]
